name: pypi-release

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  APPLICATION_NAME: kustomize_file

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: "0"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 -
          cd /usr/local/bin
          ln -s /opt/poetry/bin/poetry
      - name: Install dependencies
        run: |
          poetry install --no-dev
      - name: Build project for distribution
        run: |
          poetry run poetry build
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry run poetry publish
